title: Welcome, I'm Adam
description: > # this means to ignore newlines until "baseurl:"
  This is me, Software Developer & Engineering Science Student Adam Carnaffan.
  New technology and development excites me! Come see what I've been up to.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adamcarnaffan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Adam Carnaffan # add your name
author-img: pro_headshot.jpg # add your photo
about-author: I am a Software Developer & Engineering Science Student at the University of Toronto # add description
social-twitter: ACarnaffan # add your Twitter handle
social-facebook: Adam.Carnaffan # add your Facebook handle
social-github: Thefaceofbo # add your Github handle
social-linkedin: adam-carnaffan-b669ba176 # add your Linkedin handle
social-email: acarnaffan@hotmail.com # add your Email address

# Disqus
discus-identifier: adam-carnaffan # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
